
##################### ACROBOT
STATE_SIZE = 6
INPUT_SIZE = STATE_SIZE
ACTION_SIZE = 3
CODE_SIZE = 200
DISCRETE_CODES = True
REW_THRE = -100
WINDOW = 20
MODELS_DIR = "models/acrobot/"

Q_HIDDEN_NODES = 32
BATCH_SIZE = 64
