
##################### ACROBOT
STATE_SIZE = 3
INPUT_SIZE = STATE_SIZE
ACTION_SIZE = 3
CODE_SIZE = 200
DISCRETE_CODES = False
REW_THRE = 2000
WINDOW = 20
MODELS_DIR = "models/acrobot/"

Q_HIDDEN_NODES = 256
BATCH_SIZE = 64
MARGIN = 1 / CODE_SIZE
PREDICT_CERTAINTY = False
